[FEATURE] Update publish-version.yml

diff --git a/.github/workflows/publish-version.yml b/.github/workflows/publish-version.yml
--- a/.github/workflows/publish-version.yml
+++ b/.github/workflows/publish-version.yml
@@ -29,5 +29,40 @@ jobs:
     - name: Build app
       run: npm run build --if-present
 
-    - name: Test app
-      run: npm test
+  publish_branch:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v2
+
+    - name: Extract project version
+      id: cargo_version
+      run: |
+        PROJECT_VERSION=$(node -p "require('./package.json').version")
+        echo "Version extracted: $PROJECT_VERSION"
+        echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
+
+    - name: Check if branch already exists
+      id: check_branch
+      run: |
+        if git ls-remote --exit-code --heads https://@github.com/${{ github.repository }}.git "$PROJECT_VERSION"; then
+          echo "Branch $PROJECT_VERSION already exists. Failing job."
+          exit 1
+        fi
+      env:
+        PROJECT_VERSION: ${{ env.PROJECT_VERSION }}
+
+    - name: Create and push new branch
+      env:
+        GITHUB_TOKEN: ${{ secrets.RUSTDB_TOKEN }}
+        PROJECT_VERSION: ${{ env.PROJECT_VERSION }}
+      run: |        
+        # Configure Git
+        git config --global user.name 'github-actions[bot]'
+        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+        
+        # Create and push new branch
+        git checkout -b "$PROJECT_VERSION"
+        git remote set-url origin https://x-access-token:"$GITHUB_TOKEN"@github.com/${{ github.repository }}.git
+        git push origin "$PROJECT_VERSION"
